### ISSUE TITLE
GOReleaser

### ISSUE THREAD

**Issue by RobLoach** [libretro/go-playthemall#26]
This looks like a pretty handy tool to bundle binaries:
https://github.com/goreleaser/goreleaser

Worth a shot for building and releasing it?

**Comment by kivutar** [comment]
I really like the fact that it generates various linux packages.

Do you know if it can handle assets too?

**Comment by RobLoach** [comment]
Never used it!

**Comment by kivutar** [comment]
I took a deeper look at it. Really awesome stuff. I couldn't find if it supports assets though.

I did see a way to add the readme and copyright, the a section called `files`.

**Comment by RobLoach** [comment]
Use dep instead?

**Comment by kivutar** [comment]
dep isn't a packaging tool
